workflows:
  android-release:
    name: FF Pro Arena PK - Android APK
    max_build_duration: 60
    environment:
      flutter: 3.24.0
      java: 17
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - mujahidhayat03@gmail.com
        notify:
          success: true
          failure: true
